pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = true
    }
    stages {
        stage('build'){
            steps {
                sh 'npm install'
            }
        }
        stage('test'){
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Delivery'){
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (clicked "proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}